---
- name: ALL - Create groups
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items: "{{ groups_all.create }}"
  tags: [ groups ]

- name: ALL - Install sudo package
  package:
    name: sudo
    state: present
  when: groups_all.sudo.enabled is defined and groups_all.sudo.enabled == true
  tags: [ groups ]

- name: ALL - Configure group sudo access
  template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  with_items: "{{ groups_all.create }}"
  when: groups_all.sudo.enabled is defined and groups_all.sudo.enabled == true
  tags: [ groups ]

- name: ALL - Remove groups
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ groups_all.remove }}"
  when: groups_all.remove is defined
  tags: [ groups ]
