---
# tasks file for role
#

- include_tasks: groups-all.yml
  when: groups_all is defined

- include_tasks: groups-group.yml
  when: groups_group is defined

- include_tasks: groups-host.yml
  when: groups_host is defined
